### ISSUE TITLE
Error: Module 'FirebaseCore' not found

### ISSUE THREAD

**Issue by glenn-jocher** [firebase/mlkit-material-ios#2]
When trying to run the app on my iPhone Xs using Xcode I get this error. What should I do?

<img width="1357" alt="Screenshot 2019-05-14 at 17 55 14" src="https://user-images.githubusercontent.com/26833433/57712844-9c77f500-7671-11e9-92fe-853e6cc8eab2.png">

**Comment by paulb777** [comment]
Try Building. Xcode doesn't see modules from CocoaPods until after the first build.

**Comment by m-atlantis** [comment]
I'm getting the same error for both "FirebaseCore" and "MaterialComponents" when building.

**Comment by miworking** [comment]
Hi Glenn,

Thank you for checking this out! 

I tried to reproduce this issue locally, and I can only spot it  when openning the `ShowcaseApp.xcodeproj` directly. Have you tried to open `ShowcaseApp.xcworkspace` instead?

Another thing worth to try is to install the pods using update mode:
`pod install --repo-update`

Please let us know how it goes. 

Thanks!

Julie from ML Kit team

**Comment by glenn-jocher** [comment]
@miworking Julie thanks for the response. I don't see any file called `ShowcaseApp.xcworkspace` when I download the project, only the `ShowcaseApp.xcodepro`. Where do you see this xcworkspace file?
<img width="629" alt="Screenshot 2019-05-18 at 12 14 24" src="https://user-images.githubusercontent.com/26833433/57968108-9a11e580-7966-11e9-80d6-768ad1201054.png">

**Comment by paulb777** [comment]
`ShowcaseApp.xcworkspace` should be created after running `pod install --repo-update`.

**Comment by glenn-jocher** [comment]
@paulb777 thank you, this seemed to be the problem. I used the following commands to install successfully:

```bash
git clone https://github.com/firebase/mlkit-material-ios.git
cd mlkit-material-ios/ShowcaseApp
pod install --repo-update
```
